#!/usr/bin/env python3
"""
Water Quality System - Alert Configuration Setup Script
Helps users configure email and SMS alerts with an interactive CLI
"""

import os
import sys
import json
from pathlib import Path

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def print_header():
    print("\n" + "="*60)
    print("  🌊 WATER QUALITY SYSTEM - ALERT CONFIGURATION  🌊")
    print("="*60 + "\n")

def print_section(title):
    print("\n" + "-"*60)
    print(f"  {title}")
    print("-"*60 + "\n")

def get_yes_no(prompt):
    while True:
        response = input(f"{prompt} (y/n): ").strip().lower()
        if response in ('y', 'yes'):
            return True
        elif response in ('n', 'no'):
            return False
        print("Please enter 'y' or 'n'")

def setup_email():
    print_section("📧 EMAIL CONFIGURATION")
    
    if not get_yes_no("Do you want to set up email alerts?"):
        return None
    
    print("\n📌 Email Setup Instructions:")
    print("1. Gmail users: Enable 2-Step Verification in Account Settings")
    print("2. Gmail users: Create an App Password (not your Gmail password!)")
    print("3. Enter the credentials below\n")
    
    provider = input("Email provider (gmail/outlook/yahoo/custom) [default: gmail]: ").strip().lower() or 'gmail'
    
    config = {}
    
    if provider == 'gmail':
        config['EMAIL_HOST'] = 'smtp.gmail.com'
        config['EMAIL_PORT'] = '587'
    elif provider == 'outlook':
        config['EMAIL_HOST'] = 'smtp-mail.outlook.com'
        config['EMAIL_PORT'] = '587'
    elif provider == 'yahoo':
        config['EMAIL_HOST'] = 'smtp.mail.yahoo.com'
        config['EMAIL_PORT'] = '587'
    else:
        config['EMAIL_HOST'] = input("SMTP Host (e.g., smtp.example.com): ").strip()
        config['EMAIL_PORT'] = input("SMTP Port [default: 587]: ").strip() or '587'
    
    config['EMAIL_USER'] = input(f"Email address ({provider}): ").strip()
    config['EMAIL_PASS'] = input("Password/App Password (will not be shown): ").strip()
    config['EMAIL_FROM'] = input(f"From address [default: {config['EMAIL_USER']}]: ").strip() or config['EMAIL_USER']
    
    print("\n✅ Email configuration saved!")
    return config

def setup_sms():
    print_section("📱 SMS CONFIGURATION (TWILIO)")
    
    if not get_yes_no("Do you want to set up SMS alerts?"):
        return None
    
    print("\n📌 SMS Setup Instructions:")
    print("1. Create account at https://www.twilio.com/")
    print("2. Verify your phone number")
    print("3. Go to Account > API Keys & Tokens")
    print("4. Copy your Account SID and Auth Token")
    print("5. Get your Twilio Phone Number from Phone Numbers > Active Numbers\n")
    
    config = {}
    config['TWILIO_SID'] = input("Twilio Account SID: ").strip()
    config['TWILIO_AUTH'] = input("Twilio Auth Token (will not be shown): ").strip()
    config['TWILIO_FROM'] = input("Twilio Phone Number (e.g., +1234567890): ").strip()
    
    print("\n✅ SMS configuration saved!")
    return config

def setup_jwt():
    print_section("🔐 JWT SECURITY")
    
    if not get_yes_no("Do you want to set a custom JWT secret?"):
        return None
    
    print("\n⚠️  Keep this secret! Don't share it or commit to version control.\n")
    secret = input("Enter JWT secret (min 32 characters): ").strip()
    
    if len(secret) < 32:
        print("⚠️  Warning: Secret is less than 32 characters. Consider using a longer one.")
    
    return {'JWT_SECRET': secret}

def save_env_file(config):
    """Save configuration to .env file"""
    env_path = Path(__file__).parent / 'backend' / '.env'
    
    print(f"\n📝 Saving to: {env_path}\n")
    
    try:
        with open(env_path, 'w') as f:
            f.write("# Water Quality System - Alert Configuration\n")
            f.write("# Generated by setup script\n\n")
            
            for key, value in config.items():
                if value:
                    f.write(f"{key}={value}\n")
            
            f.write("\n# Optional: Default recipients (can be set in UI)\n")
            f.write("# ALERT_EMAILS=recipient1@example.com,recipient2@example.com\n")
            f.write("# ALERT_PHONES=+1111111111,+2222222222\n")
        
        print(f"✅ Configuration saved to {env_path}\n")
        return True
    except Exception as e:
        print(f"❌ Error saving configuration: {e}\n")
        return False

def save_alerts_json(recipients):
    """Save recipients to alerts.json"""
    alerts_path = Path(__file__).parent / 'backend' / 'alerts.json'
    
    try:
        data = {
            'emails': recipients.get('emails', []),
            'phones': recipients.get('phones', [])
        }
        
        with open(alerts_path, 'w') as f:
            json.dump(data, f, indent=2)
        
        print(f"✅ Alert recipients saved to {alerts_path}\n")
        return True
    except Exception as e:
        print(f"❌ Error saving recipients: {e}\n")
        return False

def setup_recipients():
    print_section("👥 ALERT RECIPIENTS SETUP")
    
    recipients = {'emails': [], 'phones': []}
    
    # Setup emails
    if get_yes_no("Add email recipients?"):
        print("\nEnter email addresses (one per line, empty line to finish):")
        while True:
            email = input("  Email: ").strip()
            if not email:
                break
            recipients['emails'].append(email)
            print(f"  ✓ Added: {email}")
    
    # Setup SMS
    if get_yes_no("Add SMS recipients?"):
        print("\nEnter phone numbers in international format (e.g., +1234567890)")
        print("(one per line, empty line to finish):")
        while True:
            phone = input("  Phone: ").strip()
            if not phone:
                break
            recipients['phones'].append(phone)
            print(f"  ✓ Added: {phone}")
    
    if recipients['emails'] or recipients['phones']:
        print("\n📋 Recipients Summary:")
        if recipients['emails']:
            print(f"  📧 Emails: {', '.join(recipients['emails'])}")
        if recipients['phones']:
            print(f"  📱 Phones: {', '.join(recipients['phones'])}")
        
        return recipients
    
    return None

def show_test_instructions():
    print_section("🧪 TESTING YOUR ALERTS")
    
    print("To test your alerts configuration:\n")
    print("1. Start the backend server:")
    print("   cd backend")
    print("   python app.py\n")
    
    print("2. Open the dashboard at http://localhost:3000\n")
    
    print("3. Click '🚨 Alerts' button\n")
    
    print("4. Go to 'Recipients' tab\n")
    
    print("5. Click 'Send Test Alert' button\n")
    
    print("6. Check your email/phone for test message\n")
    
    print("7. If not received, check:")
    print("   - Backend console for error messages")
    print("   - Email spam folder")
    print("   - Twilio logs at https://www.twilio.com/console/logs\n")

def main():
    clear_screen()
    print_header()
    
    config = {}
    
    # Get email config
    email_config = setup_email()
    if email_config:
        config.update(email_config)
    
    # Get SMS config
    sms_config = setup_sms()
    if sms_config:
        config.update(sms_config)
    
    # Get JWT secret
    jwt_config = setup_jwt()
    if jwt_config:
        config.update(jwt_config)
    
    # Setup recipients
    recipients = setup_recipients()
    
    # Save configuration
    if config:
        print_section("💾 SAVING CONFIGURATION")
        if save_env_file(config):
            print("✅ Environment configuration saved!")
    
    if recipients:
        if save_alerts_json(recipients):
            print("✅ Alert recipients saved!")
    
    # Show test instructions
    if config or recipients:
        show_test_instructions()
    
    print("\n✨ Setup complete!\n")
    input("Press Enter to exit...")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user\n")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}\n")
        sys.exit(1)
